// Basic pipe
print 9 |> sqrt;                    // expect: 3

// Pipe with args
print substr("hello world", 0, 5); // expect: hello
print "hello world" |> substr(0, 5); // expect: hello

// Multi-line pipe
var result = "hello"
  |> len;
print result;                       // expect: 5

// Compose
var double_sqrt = sqrt >> sqrt;
print 256 |> double_sqrt;          // expect: 4

// Compose with pipe
print 65536 |> sqrt >> sqrt;       // expect: 16
